### ISSUE TITLE
mkcli hangs and doesn't compile anything

### ISSUE THREAD

**Issue by scottatron** [mkdoc/mkcli#1] opened 2017-05-27 13:52 UTC
I've been trying to get started, but `mkcli` just seems to hang and never output or compile anything.

I've tried using the examples from the README, the argv example, and a basic example of my own, with no luck.

I am able to get output if I use `mkcat` and pipe the output to `mkcli`, but not when I just use `mkcli` on it's own.

Have also tried a couple of different Node versions—v7.10.0, v6.10.3, and v0.12.18—but get the same behaviour with each.

Any suggestions for trying to debug this further?

**Comment by tmpfs** [comment] 2017-05-28 00:45
Hi Scott,

Thanks for the report, no idea on this one. I will take a look. I have used it extensively and had no problems, are you using windows?

**Comment by scottatron** [comment] 2017-05-28 02:36
Yeah it's an odd one—I'm on macOS, but I also tried in a Docker container ([node:7-alpine](https://hub.docker.com/_/node/)) and had the same issue. 

Tried stepping through using the VSCode debugger too, but wasn't able to see anywhere obvious that it was hanging.

**Comment by tmpfs** [comment] 2017-05-29 01:36
Thanks for trying, a little busy at the moment, but i should get to look at it later this week. I realised i am using the composable streams API for my projects, maybe there is an issue with setting up the file input streams when running the cli directly.

**Comment by tmpfs** [comment] 2017-05-30 00:49
Heads up - I am reproducing this so should be able to work out a fix fairly soon, looks like an issue with the stream listeners...

**Comment by tmpfs** [comment] 2017-05-30 01:00
Ok, it was actually to do with a small mistake I made during refactoring (for the shared runtime library) that meant it was expecting input from stdin.

The fix is here:

https://github.com/mkdoc/mkdoc/commit/37da9af93ec521fd9c687f28ba25002e28973c3e

And I have published `mkdoc@1.0.48` with the fix.

Thanks for your patience and let me know if you run into more issues!

**Comment by tmpfs** [comment] 2017-05-30 01:01
A quick fix for the test spec and when expecting input from stdin and `mkdoc@1.0.49` has been published.

Closing as resolved but re-open if you are still having issues.

Ta.

**Closed as completed by tmpfs** 2017-05-30 01:01 UTC
